import { initScrollReveal } from "./reveal";
import { initNavActive } from "./nav-active";
import { initChatFlatten } from "./chat-flatten";
import { initProblemAccordion } from "./problem-accordion";
import { initStatusStack } from "./status-stack";
import { initLostThread } from "./lost-thread";
import { initScrollVideos, initVideoWarmup } from "./video-autoplay";
import { initStickyScroll } from "./sticky-scroll";
import { initWishlistForm } from "./wishlist-form";

initScrollReveal();
initNavActive();
initProblemAccordion();
initChatFlatten();
initStatusStack();
initLostThread();
initScrollVideos();
initVideoWarmup();
initStickyScroll();
initWishlistForm();
